/**
 * WF-IP-TTS-02: TTS Manifest for WriFe Interactive Practice.
 *
 * Maps phrase keys → public Supabase Storage MP3 URLs.
 *
 * Two categories:
 *  - REUSED: recordings already generated for wrifeapp (Alistair/Amelia),
 *    referenced from the same shared Supabase Storage bucket.
 *  - IP-SPECIFIC: new recordings generated by scripts/generate-tts-ip.mjs.
 *    Run that script once with your ElevenLabs + Supabase service keys.
 *
 * Voice guide:
 *  - Alistair (l30f87tf05uxyknGdDw6) — warm, authoritative male: instructions, feedback
 *  - Amelia  (ZF6FPAbjXT4488VcRRnw) — bright, encouraging female: celebrations, guidance
 */

const BASE = 'https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio'

export const TTS_MANIFEST: Record<string, string> = {
  // ── REUSED from wrifeapp ─────────────────────────────────────────────────
  // Alistair: answer feedback
  'feedback--correct':        `${BASE}/alistair/feedback--correct.mp3`,
  'feedback--try-again':      `${BASE}/alistair/feedback--try-again.mp3`,

  // Amelia: XP / celebration
  'xp--earned':               `${BASE}/amelia/xp--earned.mp3`,
  'xp--streak':               `${BASE}/amelia/xp--streak.mp3`,

  // ── IP-SPECIFIC (generated by scripts/generate-tts-ip.mjs) ──────────────
  // Amelia: activity session opener
  'activity-intro':           `${BASE}/amelia/ip/activity-intro.mp3`,

  // Alistair: per-activity-type feedback on correct
  'match-complete':           `${BASE}/alistair/ip/match-complete.mp3`,
  'write-reveal':             `${BASE}/alistair/ip/write-reveal.mp3`,

  // Amelia: lesson complete — varies by star rating
  'lesson-complete--1star':   `${BASE}/amelia/ip/lesson-complete--1star.mp3`,
  'lesson-complete--2stars':  `${BASE}/amelia/ip/lesson-complete--2stars.mp3`,
  'lesson-complete--3stars':  `${BASE}/amelia/ip/lesson-complete--3stars.mp3`,

  // Alistair: boss challenge
  'boss-intro':               `${BASE}/alistair/ip/boss-intro.mp3`,

  // Amelia: boss challenge results
  'boss-complete--great':     `${BASE}/amelia/ip/boss-complete--great.mp3`,
  'boss-complete--good':      `${BASE}/amelia/ip/boss-complete--good.mp3`,
  'boss-complete--ok':        `${BASE}/amelia/ip/boss-complete--ok.mp3`,

  // Amelia: world and badge celebrations
  'world-unlocked':           `${BASE}/amelia/ip/world-unlocked.mp3`,
  'badge-unlocked':           `${BASE}/amelia/ip/badge-unlocked.mp3`,
}
